<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.ServiceDefaults\Project.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Project.Data\Project.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\img\OATLOGO-gradient.png" />
    <_ContentIncludedByDefault Remove="wwwroot\img\OATLOGO-white.png" />
  </ItemGroup>

</Project>
